[package]
name = "paint-party"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "=0.3.26"
reqwest = { version = "=0.12.5", features = ["blocking", "json"] }
egui-macroquad = "=0.15.0"
egui = "=0.28.1"


