[package]
name = "paint-party"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "=0.3.26"
egui-macroquad = "=0.15.0"
egui = "=0.28.1"
once_cell = "1.19.0"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
env_logger = "0.6"
tokio = {version = "1.39.3", features = ["net"]}
quad-net = "0.1.1"

