[package]
name = "paint-party"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-macroquad = { git = "https://github.com/ateschan/egui-macroquad.git" }
macroquad = "0.4.4"
egui = "=0.28.1"
nanoserde = "0.1.37"
quad-net = "0.1.1"
quad-url = "0.1.1"

[profile.dev.package.'*']
opt-level = 3
